### ISSUE TITLE
你好，现在似乎不能获得number

### ISSUE THREAD

**Issue by GoldenNotebook** [cuijinyu/lawBug#1]

**Comment by cuijinyu** [comment]
我尝试看看，检查一下是否是IP被封禁，另外的话，记得切换一下代理地址。

**Comment by GoldenNotebook** [comment]
@cuijinyu 而且似乎number用&gui就是行了，可以固定死

**Comment by cuijinyu** [comment]
> @cuijinyu 而且似乎number用&gui就是行了，可以固定死

我尝试看看，如果稳定的话，就可以替换原来的，想来可以增加速度。另外的话，如果速度不够快的话，可以尝试一下更换代理方式，目前的代理存活率和速度似乎都不够理想，是速度的主要瓶颈。
